### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by diegoesq017** [Overv/SteamWebAPI#12]
Hola, tu código da estos errores 
1- 	El nombre 'data' no existe en el contexto actual
2- 	No se puede convertir implícitamente el tipo 'int' en 'SteamWebAPI.SteamAPISession.LoginStatus'. Ya existe una conversión explícita (compruebe si le falta una conversión)	

public LoginStatus steamGuardRequest(String username, String password) {
            String response = steamRequest("ISteamOAuth2/GetTokenWithCredentials/v0001",
                "client_id=DE45CD61&grant_type=password&username=" + Uri.EscapeDataString(username) + "&password=" + Uri.EscapeDataString(password) + "&x_emailauthcode=0&scope=read_profile%20write_profile%20read_client%20write_client");

            if (((string) data["x_errorcode"]).Equals("steamguard_code_required")) {
                return 1;
            } else {
                return 0;
            }
        }

Te agradecería si pudieras aclararme esa duda.
Saludos.

**Comment by Overv** [comment]
Please resubmit a pull request in English.
