### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by diegoesq017** [Overv/SteamWebAPI#13]
hello, i have two problems with your code

1- The name 'data' does not exist in the current context
2- Can not implicitly convert type 'int' in 'Steam Web API.SteamAPISession.LoginStatus'. An explicit conversion exists (check for missing a conversion)

The problems are in the following method:

public LoginStatus steamGuardRequest(String username, String password) {
            String response = steamRequest("ISteamOAuth2/GetTokenWithCredentials/v0001",
                "client_id=DE45CD61&grant_type=password&username=" + Uri.EscapeDataString(username) + "&password=" + Uri.EscapeDataString(password) + "&x_emailauthcode=0&scope=read_profile%20write_profile%20read_client%20write_client");

            if (((string) data["x_errorcode"]).Equals("steamguard_code_required")) {
                return 1;
            } else {
                return 0;
            }
        }

**Comment by diegoesq017** [comment]
return 1 can´t convert int int steam web api and data don´t exist

**Comment by Overv** [comment]
I've contacted the person who wrote the broken code.

**Comment by diegoesq017** [comment]
ok, thank you, I will be pending your answer

**Comment by ErikHumphrey** [comment]
any update on this? I can't use it either because of these two errors

**Comment by Overv** [comment]
@ErikHumphrey No update yet.

**Comment by ErikHumphrey** [comment]
ah, the guy deleted his account. rip hopes of integrating steam with .net

**Comment by jpreese** [comment]
I've created PR #14 to resolve this issue.  It doesn't look like the contributor or author tried building before contributing, so I've just gone ahead and removed the method all together.

Even though we're removing a method, I wouldn't consider it a breaking change since it's a newer feature that never compiled in the first place.

**Comment by jpreese** [comment]
You guys should now be able to build the solution.
